###############################################################################
#
#                                 Makefile
#
#
#   einfaches Makefile zum Uebersetzen von C-Programmen. Dieses Makefile hier
#   inkludiert ../makefile.mk welches den eigentlichen Uerbersetzungs und
#   Linkvorgang vornimmt. Beschreibung erfolgt dort.
#
#   Aufrufoption des Makefiles:
#        make oder make all : erstellt alle .o und das ausfuehrbare Programm
#        make compile       : compiliert nur das Hauptprogramm ohne weitere
#                             Bibliotheken
#        make clean         : loescht alle erstellten Dateien (sinnvoll,
#                             wenn Softwaremodule / Bibliotheken veraendert
#                             wurden)
#
#
#   August 2017,  R. Seelig
#
###############################################################################

PROJECT         = image2c

#SRCS            =

MATH            = 0
NCURSES         = 0
SDL             = 0

INCLUDE_PATHS   = -I./ -I../include

include ../makefile.mk

